### ISSUE TITLE
Palworld/Bug Backup to S3 Not Working in Newer Regions

### ISSUE THREAD

**Issue by PieterKuyperAlbertyn** [TheSudoYT/terraform-aws-palworld#15]
[palworld_backup_log.log](https://github.com/TheSudoYT/terraform-aws-palworld/files/14232373/palworld_backup_log.log)
[main.tf.txt](https://github.com/TheSudoYT/terraform-aws-palworld/files/14232374/main.tf.txt)
![image](https://github.com/TheSudoYT/terraform-aws-palworld/assets/103583271/5cabb47c-a8dc-49b7-b8d0-1adffc13ba3f)

**Comment by Josh-Tracy** [comment]
Thank you for pointing this out.  I won't bore you with the details, but if you're curious about what the problem was it is detailed in the PR linked to this issue. Once the PR is merged a new release version will be published automatically. You have 2 options to get this working:

## Option 1
Delete your server and rerun terraform apply to get a new server with the new user_data script. This will build a new  `/palworld-server/palworld_backup_script.sh` on your server with the fix applied. 

## Option 2
SSH into your server and edit the existing backup script located in `/palworld-server/palworld_backup_script.sh` and look for these lines:

```
aws s3 cp "\$BACKUP_FILENAME" s3://"\$S3_BUCKET_NAME"/ 
aws s3 cp "\$GUS_BACKUP" s3://"\$S3_BUCKET_NAME"/ 
```

and add `--region af-south-1` to the end of both of them. Example:

```
aws s3 cp "\$BACKUP_FILENAME" s3://"\$S3_BUCKET_NAME"/ --region af-south-1
aws s3 cp "\$GUS_BACKUP" s3://"\$S3_BUCKET_NAME"/ --region af-south-1
```
